runtime: python37  # TODO:
env: standard
service: サービス名  # TODO:
entrypoint: gunicorn -b :$PORT main:app

# 
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic